### ISSUE TITLE
Latest ITIS table drops ID's

### ISSUE THREAD

**Issue by karinorman** [ropensci/taxadb#61]
The ITIS table created by the current script in `data-raw` drops some ids. CSV contains some example scientific names that could previously be resolved.
[ex_missing_ids.csv.zip](https://github.com/cboettig/taxadb/files/3637841/ex_missing_ids.csv.zip)

**Comment by cboettig** [comment]
ok, now try:

```{r}
# update database
taxadb::td_create("itis", "dwc", overwrite = TRUE)

download.file("https://github.com/cboettig/taxadb/files/3637841/ex_missing_ids.csv.zip", "kari.csv.zip")
unzip("kari.csv.zip")
kari <- read_csv("ex_missing_ids.csv")
matches <- taxadb::get_ids(kari$scientificName, "itis")
```
I think all but one of them is now resolvable to an ID that way.  (the one that doesn't might be a due to multiple resolution; but I didn't check).   


Looks like the `data-raw/itis.R` script is still rather untidy. In particular, there was a very lazy step I had where the last part was a bit circular -- it was reading from taxadb database and not the data just created. anyway I fixed that and re-ran things and re-uploaded the archive.  I don't think it would be too hard to clean up the data-raw script a little more so it's closer to being a user-runnable update function...

**Comment by karinorman** [comment]
I think that's resolved the vast majority of dropped id's! (If not all of them, hard to do a quick check of potential multiple resolution situations)
