### ISSUE TITLE
Reviewer to do

### ISSUE THREAD

**Issue by karinorman** [ropensci/taxadb#64]
**General**
- [x] deal with vignettes, either by checking that existing vignettes will pass CRAN, or creating another version with a toy ITIS that will run

- [x] add contribution guidelines (w/ `URL`, `BugReports`, and `Maintainer`)

**Reviewer 1**

- [x] examples for `mutate_db`  and `taxa_tbl`, update examples for `td_connect` and `td_create`

- [x] backend descriptions in `schema.rmd`, and briefly in README? include info on how often database will be updated and general DWC column descriptions

- [x] add provider descriptions to README w/citations

- [x] add tests for `mutate_db()`, `quick_db()`, and `has_tbl()`

- [x] change `by_*` naming convention to `filter_*`

- [ ] suppress  warnings from `td_create`

- [x] delete code for `null_tibble()`

- [x] option for manually closing database connection (this probably already exists but is also probably different depending on provider?)

**Reviewer 2**

- [x] explicitly state location of database in README? (or just point them to `td_create` documentation)

- [ ] test again on windows, can we replicate the issues? (install and `td_create` errors)

- [x] add clean common names example to `mutate_db` documentation

**Comment by cboettig** [comment]
Additionally, I think we need to tackle the versioning database thing.  I can try to take a crack at that...  in doing so, we might want to cut a new update of some of the backends as well now.  I think there's newer COL and OTT releases already, and GBIF, ITIS, NCBI are rolling updates and could probably be updated.


quickly re database disconnect -- we do have `td_disconnect()` but it's not currently exported (and might need documentation).  I also kinda recall that issue is particularly annoying for monetdblite which doesn't allow concurrent connections, (though I think we found a workaround at some point), and shouldn't matter so much once duckdb replaces monet...)

**Comment by cboettig** [comment]
Done. and versioning done too.
